-- MySQL Script generated by MySQL Workbench
-- Tue Sep 22 12:07:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PSSSdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PSSSdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PSSSdb` DEFAULT CHARACTER SET utf8 ;
USE `PSSSdb` ;

-- -----------------------------------------------------
-- Table `PSSSdb`.`Utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PSSSdb`.`Utente` (
  `idUtente` INT NOT NULL AUTO_INCREMENT,
  `Password` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Docente` INT NULL,
  `MediaScoreLezioni` FLOAT NULL,
  `ContoPaypal` VARCHAR(45) NULL,
  `Corriculum` LONGBLOB NULL,
  PRIMARY KEY (`idUtente`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PSSSdb`.`Topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PSSSdb`.`Topic` (
  `idTopic` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idTopic`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PSSSdb`.`SubscriptionUtenteTopic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PSSSdb`.`SubscriptionUtenteTopic` (
  `idSubscriptionUtenteTopic` INT NOT NULL AUTO_INCREMENT,
  `Utente_idUtente` INT NOT NULL,
  `Topic_idTopic` INT NOT NULL,
  `Data` DATE NULL,
  UNIQUE INDEX `idSubscriptionUtenteTopic_UNIQUE` (`idSubscriptionUtenteTopic` ASC),
  INDEX `fk_SubscriptionUtenteTopic_Utente1_idx` (`Utente_idUtente` ASC),
  INDEX `fk_SubscriptionUtenteTopic_Topic1_idx` (`Topic_idTopic` ASC),
  PRIMARY KEY (`Topic_idTopic`, `Utente_idUtente`),
  CONSTRAINT `fk_SubscriptionUtenteTopic_Utente1`
    FOREIGN KEY (`Utente_idUtente`)
    REFERENCES `PSSSdb`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SubscriptionUtenteTopic_Topic1`
    FOREIGN KEY (`Topic_idTopic`)
    REFERENCES `PSSSdb`.`Topic` (`idTopic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PSSSdb`.`Lezione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PSSSdb`.`Lezione` (
  `idLezione` INT NOT NULL AUTO_INCREMENT,
  `NomeLezione` VARCHAR(45) NOT NULL,
  `Prezzo` INT NOT NULL,
  `MediaScoreLezione` FLOAT NULL,
  `NMaxStudenti` INT NULL,
  `Topic_idTopic` INT NOT NULL,
  `Utente_idUtente` INT NOT NULL,
  INDEX `fk_Lezione_Topic1_idx` (`Topic_idTopic` ASC),
  UNIQUE INDEX `idLezione_UNIQUE` (`idLezione` ASC),
  PRIMARY KEY (`idLezione`),
  INDEX `fk_Lezione_Utente1_idx` (`Utente_idUtente` ASC),
  CONSTRAINT `fk_Lezione_Topic1`
    FOREIGN KEY (`Topic_idTopic`)
    REFERENCES `PSSSdb`.`Topic` (`idTopic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lezione_Utente1`
    FOREIGN KEY (`Utente_idUtente`)
    REFERENCES `PSSSdb`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PSSSdb`.`VideoCall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PSSSdb`.`VideoCall` (
  `NomeRoom` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NULL,
  `Lezione_idLezione` INT NOT NULL,
  PRIMARY KEY (`NomeRoom`),
  INDEX `fk_VideoCall_Lezione1_idx` (`Lezione_idLezione` ASC),
  UNIQUE INDEX `Lezione_idLezione_UNIQUE` (`Lezione_idLezione` ASC),
  CONSTRAINT `fk_VideoCall_Lezione1`
    FOREIGN KEY (`Lezione_idLezione`)
    REFERENCES `PSSSdb`.`Lezione` (`idLezione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PSSSdb`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PSSSdb`.`Pagamento` (
  `Lezione_idLezione` INT NOT NULL,
  `Utente_idUtente` INT NOT NULL,
  `DataPagamento` TIMESTAMP NULL,
  `idPagamento` INT NULL AUTO_INCREMENT,
  INDEX `fk_Pagamento_Lezione1_idx` (`Lezione_idLezione` ASC),
  INDEX `fk_Pagamento_Utente1_idx` (`Utente_idUtente` ASC),
  PRIMARY KEY (`Lezione_idLezione`, `Utente_idUtente`),
  UNIQUE INDEX `idPagamento_UNIQUE` (`idPagamento` ASC),
  CONSTRAINT `fk_Pagamento_Lezione1`
    FOREIGN KEY (`Lezione_idLezione`)
    REFERENCES `PSSSdb`.`Lezione` (`idLezione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagamento_Utente1`
    FOREIGN KEY (`Utente_idUtente`)
    REFERENCES `PSSSdb`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PSSSdb`.`Recensione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PSSSdb`.`Recensione` (
  `Lezione_idLezione` INT NOT NULL,
  `Utente_idUtente` INT NOT NULL,
  `idRecensione` INT NULL AUTO_INCREMENT,
  `Valutazione` INT NULL,
  INDEX `fk_Recensione_Lezione1_idx` (`Lezione_idLezione` ASC),
  INDEX `fk_Recensione_Utente1_idx` (`Utente_idUtente` ASC),
  PRIMARY KEY (`Lezione_idLezione`, `Utente_idUtente`),
  UNIQUE INDEX `idRecensione_UNIQUE` (`idRecensione` ASC),
  CONSTRAINT `fk_Recensione_Lezione1`
    FOREIGN KEY (`Lezione_idLezione`)
    REFERENCES `PSSSdb`.`Lezione` (`idLezione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recensione_Utente1`
    FOREIGN KEY (`Utente_idUtente`)
    REFERENCES `PSSSdb`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PSSSdb`.`FasciaOraria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PSSSdb`.`FasciaOraria` (
  `Lezione_Data` DATE NOT NULL,
  `Orario` INT NOT NULL,
  `Utente_idUtente` INT NOT NULL,
  `Lezione_idLezione1` INT NOT NULL,
  PRIMARY KEY (`Lezione_Data`, `Orario`, `Utente_idUtente`),
  INDEX `fk_FasciaOraria_Utente1_idx` (`Utente_idUtente` ASC),
  INDEX `fk_FasciaOraria_Lezione1_idx` (`Lezione_idLezione1` ASC),
  CONSTRAINT `fk_FasciaOraria_Utente1`
    FOREIGN KEY (`Utente_idUtente`)
    REFERENCES `PSSSdb`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FasciaOraria_Lezione1`
    FOREIGN KEY (`Lezione_idLezione1`)
    REFERENCES `PSSSdb`.`Lezione` (`idLezione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
