-- MySQL Script generated by MySQL Workbench
-- Thu Sep 24 16:18:11 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Prova2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Prova2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Prova2` DEFAULT CHARACTER SET utf8 ;
USE `Prova2` ;

-- -----------------------------------------------------
-- Table `Prova2`.`Utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova2`.`Utente` (
  `idUtente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Cognome` VARCHAR(45) NULL,
  PRIMARY KEY (`idUtente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prova2`.`Topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova2`.`Topic` (
  `idTopic` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`idTopic`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prova2`.`SubscriptionUtenteTopic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova2`.`SubscriptionUtenteTopic` (
  `idSubscriptionUtenteTopic` INT NOT NULL AUTO_INCREMENT,
  `Utente_idUtente` INT NOT NULL,
  `Topic_idTopic` INT NOT NULL,
  `Data` DATE NULL,
  UNIQUE INDEX `idSubscriptionUtenteTopic_UNIQUE` (`idSubscriptionUtenteTopic` ASC),
  INDEX `fk_SubscriptionUtenteTopic_Utente1_idx` (`Utente_idUtente` ASC),
  INDEX `fk_SubscriptionUtenteTopic_Topic1_idx` (`Topic_idTopic` ASC),
  PRIMARY KEY (`Topic_idTopic`, `Utente_idUtente`),
  CONSTRAINT `fk_SubscriptionUtenteTopic_Utente1`
    FOREIGN KEY (`Utente_idUtente`)
    REFERENCES `Prova2`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SubscriptionUtenteTopic_Topic1`
    FOREIGN KEY (`Topic_idTopic`)
    REFERENCES `Prova2`.`Topic` (`idTopic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prova2`.`Lezione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova2`.`Lezione` (
  `idLezione` INT NOT NULL AUTO_INCREMENT,
  `NomeLezione` VARCHAR(45) NOT NULL,
  `MediaScoreLezione` FLOAT NULL,
  `NMaxStudenti` INT NULL,
  `Topic_idTopic` INT NOT NULL,
  INDEX `fk_Lezione_Topic1_idx` (`Topic_idTopic` ASC),
  UNIQUE INDEX `idLezione_UNIQUE` (`idLezione` ASC),
  PRIMARY KEY (`idLezione`),
  CONSTRAINT `fk_Lezione_Topic1`
    FOREIGN KEY (`Topic_idTopic`)
    REFERENCES `Prova2`.`Topic` (`idTopic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prova2`.`VideoCall`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova2`.`VideoCall` (
  `NomeRoom` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NULL,
  `Lezione_idLezione` INT NOT NULL,
  PRIMARY KEY (`NomeRoom`),
  INDEX `fk_VideoCall_Lezione1_idx` (`Lezione_idLezione` ASC),
  UNIQUE INDEX `Lezione_idLezione_UNIQUE` (`Lezione_idLezione` ASC),
  CONSTRAINT `fk_VideoCall_Lezione1`
    FOREIGN KEY (`Lezione_idLezione`)
    REFERENCES `Prova2`.`Lezione` (`idLezione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prova2`.`FasciaOraria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova2`.`FasciaOraria` (
  `idFasciaOraria` INT NOT NULL,
  `Data` DATE NOT NULL,
  `Orario` INT NOT NULL,
  `DescrizioneLezione_idDescrizioneLezione` INT NOT NULL,
  `DescrizioneLezione_Utente_idUtente` INT NOT NULL,
  UNIQUE INDEX `idFasciaOraria_UNIQUE` (`idFasciaOraria` ASC),
  PRIMARY KEY (`Data`, `Orario`, `DescrizioneLezione_idDescrizioneLezione`, `DescrizioneLezione_Utente_idUtente`),
  INDEX `fk_FasciaOraria_DescrizioneLezione1_idx` (`DescrizioneLezione_idDescrizioneLezione` ASC, `DescrizioneLezione_Utente_idUtente` ASC),
  CONSTRAINT `fk_FasciaOraria_DescrizioneLezione1`
    FOREIGN KEY (`DescrizioneLezione_idDescrizioneLezione` , `DescrizioneLezione_Utente_idUtente`)
    REFERENCES `Prova2`.`DescrizioneLezione` (`idDescrizioneLezione` , `Utente_idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prova2`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova2`.`Pagamento` (
  `DataPagamento` TIMESTAMP NULL,
  `idPagamento` INT NULL AUTO_INCREMENT,
  `FasciaOraria_DataLezione` DATE NOT NULL,
  `FasciaOraria_OrarioLezione` INT NOT NULL,
  `FasciaOraria_Utente_idUtente` INT NOT NULL,
  `Utente_idUtente` INT NOT NULL,
  UNIQUE INDEX `idPagamento_UNIQUE` (`idPagamento` ASC),
  PRIMARY KEY (`FasciaOraria_DataLezione`, `FasciaOraria_OrarioLezione`, `FasciaOraria_Utente_idUtente`, `Utente_idUtente`),
  INDEX `fk_Pagamento_Utente1_idx` (`Utente_idUtente` ASC),
  CONSTRAINT `fk_Pagamento_FasciaOraria1`
    FOREIGN KEY (`FasciaOraria_DataLezione` , `FasciaOraria_OrarioLezione` , `FasciaOraria_Utente_idUtente`)
    REFERENCES `Prova2`.`FasciaOraria` (`DataLezione` , `OrarioLezione` , `Utente_idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagamento_Utente1`
    FOREIGN KEY (`Utente_idUtente`)
    REFERENCES `Prova2`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prova2`.`Recensione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova2`.`Recensione` (
  `Lezione_idLezione` INT NOT NULL,
  `Utente_idUtente` INT NOT NULL,
  `idRecensione` INT NULL AUTO_INCREMENT,
  `Valutazione` INT NULL,
  INDEX `fk_Recensione_Lezione1_idx` (`Lezione_idLezione` ASC),
  INDEX `fk_Recensione_Utente1_idx` (`Utente_idUtente` ASC),
  PRIMARY KEY (`Lezione_idLezione`, `Utente_idUtente`),
  UNIQUE INDEX `idRecensione_UNIQUE` (`idRecensione` ASC),
  CONSTRAINT `fk_Recensione_Lezione1`
    FOREIGN KEY (`Lezione_idLezione`)
    REFERENCES `Prova2`.`Lezione` (`idLezione`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recensione_Utente1`
    FOREIGN KEY (`Utente_idUtente`)
    REFERENCES `Prova2`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prova2`.`Orario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova2`.`Orario` (
  `Data` INT NOT NULL,
  `Orario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Data`, `Orario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prova2`.`Utente_has_Orario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova2`.`Utente_has_Orario` (
  `Utente_idUtente` INT NOT NULL,
  `Orario_Data` INT NOT NULL,
  `Orario_Orario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Utente_idUtente`, `Orario_Data`, `Orario_Orario`),
  INDEX `fk_Utente_has_Orario_Orario1_idx` (`Orario_Data` ASC, `Orario_Orario` ASC),
  INDEX `fk_Utente_has_Orario_Utente1_idx` (`Utente_idUtente` ASC),
  CONSTRAINT `fk_Utente_has_Orario_Utente1`
    FOREIGN KEY (`Utente_idUtente`)
    REFERENCES `Prova2`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utente_has_Orario_Orario1`
    FOREIGN KEY (`Orario_Data` , `Orario_Orario`)
    REFERENCES `Prova2`.`Orario` (`Data` , `Orario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prova2`.`Utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova2`.`Utente` (
  `idUtente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Cognome` VARCHAR(45) NULL,
  PRIMARY KEY (`idUtente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prova2`.`DescrizioneLezione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova2`.`DescrizioneLezione` (
  `idDescrizioneLezione` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Utente_idUtente` INT NOT NULL,
  PRIMARY KEY (`idDescrizioneLezione`, `Utente_idUtente`),
  INDEX `fk_Lezione_Utente1_idx` (`Utente_idUtente` ASC),
  UNIQUE INDEX `idDescrizioneLezione_UNIQUE` (`idDescrizioneLezione` ASC),
  CONSTRAINT `fk_Lezione_Utente1`
    FOREIGN KEY (`Utente_idUtente`)
    REFERENCES `Prova2`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prova2`.`FasciaOraria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova2`.`FasciaOraria` (
  `idFasciaOraria` INT NOT NULL,
  `Data` DATE NOT NULL,
  `Orario` INT NOT NULL,
  `DescrizioneLezione_idDescrizioneLezione` INT NOT NULL,
  `DescrizioneLezione_Utente_idUtente` INT NOT NULL,
  UNIQUE INDEX `idFasciaOraria_UNIQUE` (`idFasciaOraria` ASC),
  PRIMARY KEY (`Data`, `Orario`, `DescrizioneLezione_idDescrizioneLezione`, `DescrizioneLezione_Utente_idUtente`),
  INDEX `fk_FasciaOraria_DescrizioneLezione1_idx` (`DescrizioneLezione_idDescrizioneLezione` ASC, `DescrizioneLezione_Utente_idUtente` ASC),
  CONSTRAINT `fk_FasciaOraria_DescrizioneLezione1`
    FOREIGN KEY (`DescrizioneLezione_idDescrizioneLezione` , `DescrizioneLezione_Utente_idUtente`)
    REFERENCES `Prova2`.`DescrizioneLezione` (`idDescrizioneLezione` , `Utente_idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
