-- MySQL Script generated by MySQL Workbench
-- Thu Sep 24 16:26:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Prova2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Prova2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Prova2` DEFAULT CHARACTER SET utf8 ;
USE `Prova2` ;

-- -----------------------------------------------------
-- Table `Prova2`.`Utente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova2`.`Utente` (
  `idUtente` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Cognome` VARCHAR(45) NULL,
  PRIMARY KEY (`idUtente`),
  UNIQUE INDEX `idUtente_UNIQUE` (`idUtente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prova2`.`DescrizioneLezione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova2`.`DescrizioneLezione` (
  `idDescrizioneLezione` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Utente_idUtente` INT NOT NULL,
  PRIMARY KEY (`idDescrizioneLezione`, `Utente_idUtente`),
  INDEX `fk_DescrizioneLezione_Utente_idx` (`Utente_idUtente` ASC),
  UNIQUE INDEX `idDescrizioneLezione_UNIQUE` (`idDescrizioneLezione` ASC),
  CONSTRAINT `fk_DescrizioneLezione_Utente`
    FOREIGN KEY (`Utente_idUtente`)
    REFERENCES `Prova2`.`Utente` (`idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prova2`.`FasciaOraria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Prova2`.`FasciaOraria` (
  `Data` DATE NOT NULL,
  `Orario` INT NOT NULL,
  `DescrizioneLezione_idDescrizioneLezione` INT NOT NULL,
  `DescrizioneLezione_Utente_idUtente` INT NOT NULL,
  PRIMARY KEY (`Data`, `DescrizioneLezione_Utente_idUtente`, `Orario`),
  INDEX `fk_FasciaOraria_DescrizioneLezione1_idx` (`DescrizioneLezione_idDescrizioneLezione` ASC, `DescrizioneLezione_Utente_idUtente` ASC),
  CONSTRAINT `fk_FasciaOraria_DescrizioneLezione1`
    FOREIGN KEY (`DescrizioneLezione_idDescrizioneLezione` , `DescrizioneLezione_Utente_idUtente`)
    REFERENCES `Prova2`.`DescrizioneLezione` (`idDescrizioneLezione` , `Utente_idUtente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
